# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceTypes: t3.micro
  spot: true
  desiredCapacity: 2