apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
- name: spot
  spot: true
  instanceTypes:
    - t3.medium
    - t3.large
    - t4g.medium
    - m5.large
    - m6i.large
    - c5.large
    - c6i.large
    - r5.large
    - r6i.large
  desiredCapacity: 2
  minSize: 2
  maxSize: 4
