apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceTypes: ["t3.medium","t3.large","c5.large","c5a.large","c5n.large","m5.large","m5a.large"]
  spot: true
  desiredCapacity: 2
  minSize: 2
  maxSize: 4
